// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlu8O6EG-_hwHr_-3HXpIt8YlI8X1sNes',
    appId: '1:649934200358:web:10dd2bf4f3860b62d590e7',
    messagingSenderId: '649934200358',
    projectId: 'face-437c4',
    authDomain: 'face-437c4.firebaseapp.com',
    storageBucket: 'face-437c4.firebasestorage.app',
    measurementId: 'G-3TMEGWM3K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFS8wQth0rF2Ms2vEG4U6OdsKEiI4cjQk',
    appId: '1:649934200358:android:abfc90e93ef09a7bd590e7',
    messagingSenderId: '649934200358',
    projectId: 'face-437c4',
    storageBucket: 'face-437c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh8LzBvbB0QMn7Sj4Kd5sPDryiJ-noT54',
    appId: '1:649934200358:ios:be83b8f59aa0bd98d590e7',
    messagingSenderId: '649934200358',
    projectId: 'face-437c4',
    storageBucket: 'face-437c4.firebasestorage.app',
    iosBundleId: 'com.example.face',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh8LzBvbB0QMn7Sj4Kd5sPDryiJ-noT54',
    appId: '1:649934200358:ios:be83b8f59aa0bd98d590e7',
    messagingSenderId: '649934200358',
    projectId: 'face-437c4',
    storageBucket: 'face-437c4.firebasestorage.app',
    iosBundleId: 'com.example.face',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlu8O6EG-_hwHr_-3HXpIt8YlI8X1sNes',
    appId: '1:649934200358:web:4b6561454d6b7831d590e7',
    messagingSenderId: '649934200358',
    projectId: 'face-437c4',
    authDomain: 'face-437c4.firebaseapp.com',
    storageBucket: 'face-437c4.firebasestorage.app',
    measurementId: 'G-9GV7BPTCXX',
  );
}
